name: BackUP
main: me.hteppl.backup.Loader
version: "${pom.version}"
api: 1.0.13
authors:
  - "https://github.com/hteppl"
  - "https://github.com/IWareQ"
website: "https://github.com/hteppl/DataManager"
